---
name: Build

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  actions: read

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build
        run: go build -o dist/BillingLinux ./cmd

      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -o dist/BillingWindows.exe ./cmd

      - name: Upload a Linux Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BillingLinux
          path: dist/BillingLinux

      - name: Upload a Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BillingWindows
          path: dist/BillingWindows.exe
